### ISSUE TITLE
No portaudio on macOS

### ISSUE THREAD

**Issue by cbrnr** [conda-forge/psychopy-feedstock#35]
I'm not sure if this is the right place to report this issue, but I am unable to `conda install psychopy` (the channel is set to `conda-forge`), because:

```
Problem: nothing provides portaudio needed by python-sounddevice-0.3.10-py_0
```

Indeed, that seems to be true (https://anaconda.org/conda-forge/portaudio), but it also means that I cannot install PsychoPy on macOS. I'm not a regular `conda-forge` user, but AFAIK this used to work a couple of months ago.

@hoechenberger maybe?

Details about  <code>conda</code> and system (<code>conda info</code>):
<details>

```
$ conda info
     active environment : base
    active env location : /Users/clemens/anaconda
            shell level : 1
       user config file : /Users/clemens/.condarc
 populated config files : /Users/clemens/anaconda/.condarc
          conda version : 4.9.2
    conda-build version : not installed
         python version : 3.9.0.final.0
       virtual packages : __osx=10.16=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /Users/clemens/anaconda  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /Users/clemens/anaconda/pkgs
                          /Users/clemens/.conda/pkgs
       envs directories : /Users/clemens/anaconda/envs
                          /Users/clemens/.conda/envs
               platform : osx-64
             user-agent : conda/4.9.2 requests/2.25.0 CPython/3.9.0 Darwin/20.1.0 OSX/10.16
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```
</details>

**Comment by cbrnr** [comment]
It looks like `portaudio` on `conda-forge` doesn't have macOS builds, so usually `conda` fetches the package from the `default` channel. However, this doesn't work when using [miniforge](https://github.com/conda-forge/miniforge), because this distribution only activates the `conda-forge` channel (i.e. not `default`).

I've now added the default channel and everything works. However, it would be nice if `portaudio` was also available on `conda-forge` (because mixing channels is almost never a good idea). There's already an open issue: https://github.com/conda-forge/portaudio-feedstock/issues/2. Basically, someone would need to copy the recipe from the default channel and ideally everything should work.

**Comment by hoechenberger** [comment]
@cbrnr https://github.com/conda-forge/portaudio-feedstock/issues/2 is closed now and there's now a `portaudio` build for macOS on `conda-forge`. Does this resolve this issue?

**Comment by cbrnr** [comment]
Yes! `psychopy` still doesn't start, but that's another issue (https://github.com/psychopy/psychopy/issues/3362).

**Comment by hoechenberger** [comment]
Thanks!
